Write-Host "Revisando estado de Git..."
git status --short
Write-Host ""
Write-Host "Archivos ignorados por seguridad:"
Write-Host "- .env"
Write-Host "- backend/.env"
Write-Host "- client/.env"
Write-Host ""
Write-Host "Para hacer commit seguro:"
Write-Host "git add ."
Write-Host "git diff --cached"
Write-Host "git commit -m \"tu mensaje\""
